### ISSUE TITLE
Bitcode issues with version 2.0.1

### ISSUE THREAD

**Issue by bojan** [Appboy/appboy-segment-ios#14]
Archiving an app that integrates Appboy through Segment as a pod, returns the following errors:

```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '900.0.37.0_0' Reader: '802.0.42_0')', using libLTO version 'LLVM version 8.1.0, (clang-802.0.42)' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is the only output from the logs.

**Comment by chshapiro** [comment]
Hey @bojan,

Are you using Xcode 9 when you're trying to archive the app? 
What version of our iOS SDK are you? As of version 3.1.0, we require Xcode 9 to be used.

Thanks,
Chava

**Comment by bojan** [comment]
@chshapiro nope, we're using Xcode 8.3.3. We thought this release of the Segment integration (2.0.1) was just a bugfix for the Cocoapods header issue (`Appboy_iOS_SDK` vs `Appboy-iOS-SDK`).
Is there any alternative?

**Comment by chshapiro** [comment]
Hey @bojan,

In this version, we also pull the latest version of the iOS SDK which requires Xcode 9. To get around this, you can add `pod 'Appboy-iOS-SDK', '~> 3.0.2'` to your Podfile which will pull an older version of the iOS SDK that does not require Xcode 9.

Please let us know if this fixes your issue or if you have any other questions.

Thanks,
Chava

**Comment by bojan** [comment]
Thanks @chshapiro for the help! It works now 🎉 
Could you maybe update the Readme regarding the build environment?

The configuration that worked for us for Xcode 8.3.3 was:
```
  pod 'Segment-Appboy'
  pod 'Appboy-iOS-SDK', '~> 3.0.2'
```
