### ISSUE TITLE
Use of undeclared identifier 'ABKSDKFlavorKey' ,'SEGMENT'

### ISSUE THREAD

**Issue by ghbsara** [Appboy/appboy-segment-ios#15]
Hi,

I get the following errors when building with cocoapods 1.3.1

```
Use of undeclared identifier 'ABKSDKFlavorKey'
Use of undeclared identifier 'SEGMENT'
```

Podfile :

`pod 'Segment-Appboy'`

- i'm using use_frameworks! in my Podfile

**Comment by chshapiro** [comment]
Hey @ghbsara,

Can you check your Podfile.lock and see what version of 'Segment-Appboy' and 'Appboy-iOS-SDK' you are pulling?

Thanks,
Chava

**Comment by ghbsara** [comment]
Appboy-iOS-SDK (2.25.0)
Segment-Appboy (2.0.0)

**Comment by chshapiro** [comment]
Hey @ghbsara,

`ABKSDKFlavorKey` was introduced in Appboy-iOS-SDK version 2.29.0. Can you run `pod update` and see if that will pull the latest version of the SDK?

Segment-Appboy 2.0.0 supports Appboy-iOS-SDK 3.0.0+ (https://github.com/Appboy/appboy-segment-ios/blob/master/CHANGELOG.md#200).

Thanks,
Chava

**Comment by ghbsara** [comment]
After running pod update :
Appboy-iOS-SDK (2.25.0) (still the same)
Segment-Appboy (2.0.1)

**Comment by chshapiro** [comment]
Hey @ghbsara,

2.25.0 is the last version that uses SDWebImage 3.x. Are you using SDWebImage in your app?

If not, I wonder if there is an issue with the Cocoapods gem on your computer. Could you follow https://guides.cocoapods.org/using/troubleshooting.html and see if that uninstall/re-install fixes the issue and let you pull the latest version of Appboy-iOS-SDK?

Thanks,
Chava

**Comment by ghbsara** [comment]
yes i'm using SDWebImage (3.7.6) in my app

**Comment by chshapiro** [comment]
Hey @ghbsara,

Appboy-Segment version 1.0.4 is the last one that can work properly together with SDWebImage 3.x.
Can you try either using SDWebImage 4.0 in your app or using Appboy-Segment 1.0.4?

Please let us know if this doesn't work or if you have any other questions.

Thanks,
Chava

**Comment by ghbsara** [comment]
Thanks @chshapiro for the help! It works now

**Comment by pvinis** [comment]
I know it's almost 4 years later, but we are having the same issue.

From Podfile.lock:
- SDWebImage (3.7.3)
- Segment-Appboy (2.0.3)
- Segment-Appboy/Full-SDK (2.0.3)
- Appboy-iOS-SDK (2.25.0)

We get the same error, undeclared identifiers for `ABKSDKFlavorKey` and `SEGMENT`.

You could even look at the code if you need, here https://github.com/artsy/eigen/pull/4732.

**Comment by chshapiro** [comment]
Hey @pvinis,

As mentioned above, if you're still using SDWebImage 3.x, you'll need to either use `Segment-Appboy` version 1.0.4 or use SDWebImage 4.0.

**Comment by pvinis** [comment]
Hm. I remember trying to use 1.0.4 but failed. I will give it another try.
