### ISSUE TITLE
No Carthage Support

### ISSUE THREAD

**Issue by JohnTheBastard** [Appboy/appboy-segment-ios#17]
Carthage support would be helpful, even if the framework is only available as a precompiled download.

**Comment by chshapiro** [comment]
Hey @JohnTheBastard,

Thank you for submitting this request! Improving ease-of-integration is a top priority for us. We'll be investigating our alternatives/executing on this over the coming months and will be in touch as we do so.

Thanks,
Chava

**Comment by alexis-letexier** [comment]
@chshapiro Any update on this ?

Thanks !

**Comment by Bucimis** [comment]
Thanks @alexis-letexier, we're still evaluating this project. What workarounds are you using currently?

**Comment by Bucimis** [comment]
Thanks for the additional context @alexis-letexier, we've added carthage support to our backlog and will keep you in the loop as things move forward. Note that we don't have an ETA at this time.

**Comment by farshadtx** [comment]
Is there any update here? any roadmap? I'm trying to choose tools for the next project and I need to know if supporting Carthage is going to happen soon.

**Comment by Bucimis** [comment]
Hi @farshadtx, we're still evaluating carthage support for segment at this time. If you are starting a project now, we'd recommend using Cocoapods or importing our source directly (this is a very simple library with only a few files).

If you need to use Carthage and having a simple .framework file would work for your needs, you can generate one through cocoapods using the Example xcworkspace or contact us for further help.

**Comment by Bucimis** [comment]
@JohnTheBastard @farshadtx @alexis-letexier hey everyone - could you shout if this is still on your radar?

**Comment by alan-andrade** [comment]
Hi!  this is on my radar now. Trying to get this working with Carthage if possible.

**Comment by popei69** [comment]
Hi there! Is there any new update for Carthage support? I'm looking into integrating Braze + Segment SDK together through this repo. Thanks!

**Comment by hokstuff** [comment]
Hi @popei69,

The dev team is currently working on adding Carthage support to the Braze + Segment SDK. We'll keep you updated for when we release it, thanks!

**Comment by chshapiro** [comment]
Hey all,

We just released version 3.2.0 of the Braze + Segment SDK which adds Carthage support. Feel free to open a new thread if you run into any issues when integrating.
