### ISSUE TITLE
Will it support tvOS?

### ISSUE THREAD

**Issue by tanduynguyen** [Appboy/appboy-segment-ios#19]
I really want to use this SDK on tvOS, please :(

**Comment by Bucimis** [comment]
@tanduynguyen were you able to find a workaround?

**Comment by mickyzinho** [comment]
Any news here? Is it possible to use the segment integration with tvOS?

**Comment by chshapiro** [comment]
Hey @mickyzinho,

This feature is on our roadmap and we will continue to update this thread as we have updates.

Thank you!

**Comment by chshapiro** [comment]
Hey @tanduynguyen @mickyzinho,

Our newest release 4.1.0 includes tvOS support. 

Please let us know if you have any further questions.
