### ISSUE TITLE
Get notified when Appboy.sharedInstance is initted

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-segment-ios#2]
I couldn't figure out a way to get notified when segment triggers `integration.initWithSettings` (which [creates the Appboy singleton](https://github.com/Appboy/appboy-segment-ios/blob/master/Pod/Classes/SEGAppboyIntegration.m#L30-L32)).

My use case is that I want to enable NUI theming app-wide, whether I open the newsfeed explicitly or when getting an inapp notification. Usually you would put the following code in `applicationDidFinishLaunching`:

```
NUISettings.initWithStylesheet("AppBoy")
Appboy.sharedInstance()?.useNUITheming = true
```

but the shared instance will most likely be `nil` at this point because Segment asynchronously creates it (it has to fetch the API key first).

Is there a way to get notified of the singleton creation at the moment?

**Comment by briancaw** [comment]
Hey @ldiqual 

Thanks for inquiring - it looks like you can subscribe to notifications that Segment fires off on integration init...see https://github.com/segmentio/analytics-ios/blob/master/Pod/Classes/SEGAnalytics.m#L379.  We haven't tested that out yet though, and we'll want check with Segment to ensure that's a supported interface.  We should be able to confirm sometime in the couple business days.

Thanks,
Brian

**Comment by f2prateek** [comment]
That's right - you can use that to be notified and use the key posted to filter out the Appboy integration.

**Comment by ldiqual** [comment]
@briancaw @f2prateek Oh, great find! Since it wasn't exposed publicly, I had to declare that key in my bridging header:

```
extern NSString *SEGAnalyticsIntegrationDidStart;
```

For reference, here's the related segment issue: https://github.com/segmentio/analytics-ios/issues/513
