### ISSUE TITLE
Support for braze 3.19.0

### ISSUE THREAD

**Issue by ignotusverum** [Appboy/appboy-segment-ios#26]
Can we please add support for v `3.19.0` <- https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.19.0

**Comment by chshapiro** [comment]
Hey @ignotusverum, 

We are working on this right now and plan to release it in the next day or two.

Thanks,
Chava

**Comment by chshapiro** [comment]
Hey @ignotusverum,

This is live now in version 2.1.0.
