### ISSUE TITLE
pod install adds an older version

### ISSUE THREAD

**Issue by ramshandilya-earnin** [Appboy/appboy-segment-ios#27]
I'm trying to install Segment-Appboy with the latest `2.1.0` version.
`Podfile` - 
```
pod 'Segment-Appboy'
```

When I run `pod install`, I see older versions of the SDKs being installed - 
```
Installing Appboy-iOS-SDK (3.16.0)
Installing Segment-Appboy (2.0.3)
```

**Comment by chshapiro** [comment]
Hey @ramshandilya-earnin,

We're unable to repro this behavior. Maybe it's a cache problem? Can you try deleting your `Pods` folder and trying again? Also what you happens if you specifically specify `2.1.0` in your Podfile?

Thanks!

**Comment by ramshandilya-earnin** [comment]
Tried `pod cache clean --all`, same result.
Also, tried with -
```
pod 'Segment-Appboy', '2.1.0'
```
Getting this error - 
```
[!] CocoaPods could not find compatible versions for pod "Segment-Appboy":
  In Podfile:
    Segment-Appboy (= 2.1.0)
```

**Comment by chshapiro** [comment]
Hey @ramshandilya-earnin,

Can you share your full Podfile?

**Comment by ramshandilya-earnin** [comment]
I'm not sure if I can share the entire podfile. I'll share what I think is relevant - 
```
platform :ios, '11.0'

source 'https://github.com/<redacted>/.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
workspace '<redacted>'

def base_pods
    pod 'Analytics', :git => 'https://github.com/<redacted>.git', :inhibit_warnings => true
    pod 'Segment-Appboy', '2.1.0'
end
```

Does this help?

**Comment by ramshandilya-earnin** [comment]
I believe it uses `3.6.10` and not `3.7.0`of `Analytics`. Do you think that's causing this?
Deleting `Podfile.lock` didn't help as well.

**Comment by chshapiro** [comment]
I don't think - when I use `3.6.10` everything works fine.
Do you support iOS 8 in your app? And are you pulling in SDWebImage in your Podfile?

**Comment by ramshandilya-earnin** [comment]
We're supporting iOS 11 and up.
We're not adding `SDWebImage` in the Podfile either.
`pod update` also didn't help

**Comment by ramshandilya-earnin** [comment]
I tried on a new project and it looks like I'm not facing this issue there. So I guess it's something wrong with our repo then.

**Comment by ramshandilya-earnin** [comment]
That said, any pointer to why we're facing this would be helpful.
Thanks!
