### ISSUE TITLE
[Request] Implement Swift Package Manager Support

### ISSUE THREAD

**Issue by bdrelling** [Appboy/appboy-segment-ios#29]
Just wondering if (or when?) we'll get Swift Package Manager support for this library. (Specifically `Core`, not `UI`.)

**Comment by Bucimis** [comment]
@bdrelling thanks for raising! SPM support is on our product roadmap but we don't have an estimate at this time

**Comment by bdrelling** [comment]
@Bucimis Just wanted to know if this was in the works at all? 🤞

**Comment by Bucimis** [comment]
@bdrelling still in our roadmap at this point, my best guess would be sometime during H1. Thanks for your patience and for checking in

**Comment by matiasvillaverde** [comment]
@Bucimis Do we have an update on this? This will be a really nice feature

**Comment by Bucimis** [comment]
@matiasvillaverde thanks for getting in touch! This is still on our roadmap but may slip a bit from the timeline I mentioned earlier - we pushed back our work on SPM support for `appboy-ios-sdk` (which this library depends on) while waiting for first-class binary dependency support in SPM, which we need since that library is only partially open-sourced.

**Comment by bdrelling** [comment]
@Bucimis This is now causing active downgrades in our repo due to the decision to try out the `InAppMessage` spec, which pulls in `SDWebImage` from CocoaPods, thereby forcing us to remove `SDWebImage` from SPM.

In the meantime while waiting for 5.3 which includes binary dependency support, can you change the dependencies in your spec such that we could use our own version of `SDWebImage` in SPM and not be forced until duplication of the frameworks and another dependency back in CocoaPods?

**Comment by bdrelling** [comment]
@Bucimis how we looking on this one? Any chance of getting it soon? 🤞🏻

**Comment by Bucimis** [comment]
@bdrelling we just released support for SPM for the iOS SDK last week and this SDK is next in line (and should be much simpler). I don't have an exact timeline but it's definitely on our roadmap for the next few months

**Comment by chshapiro** [comment]
Hey @bdrelling and @integer256,

We just released version 3.6.0 of the SDK which adds support for Swift Package Manager 🎉 . 
Please feel free to open a new issue if you run into any problems when integrating.

Thanks!
