### ISSUE TITLE
Missing arm64 symbols for appboy-ios-sdk and failing with Xcode 12

### ISSUE THREAD

**Issue by mrunalabhatt** [Appboy/appboy-segment-ios#40]
I have recently downloaded Xcode 12.4 and updated all my Pods to latest. One of Pod was having entry for segment

```
platform :ios, '14'
pod 'Segment-Appboy', '~> 3.3'
```

This Pod internally has dependency with appboy-ios-sdk, so once after pod install succeeded, building through Xcode gives below compile error for build target appboy-ios-sdk:

```
ld: in /Pods/Appboy-iOS-SDK/AppboyKit/libAppboyKitLibrary.a(ABKInAppMessageHTMLBase.o), building for iOS Simulator, but linking in object file built for iOS, file '//AppboyKit/libAppboyKitLibrary.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Which Segment pod version should I connect to support iOS 14 and XCode 12 ?

Ref: https://github.com/Appboy/appboy-ios-sdk/issues/245

**Comment by chshapiro** [comment]
Hey @mrunalabhatt,

Our `Segment-Appboy` pod is not currently compatible with Xcode 12. We have released a beta `Appboy-iOS-SDK` that can be used to test on Xcode 12. If you'd like to test with that, you can add `pod 'Appboy-iOS-SDK', '3.27.0-beta1'` to your Podfile and it'll override the version of `Appboy-iOS-SDK` used in the `Segment-Appboy` pod.

We plan to release a version of `Segment-Appboy` that's compatible with Xcode 12 soon after the iOS 14 GM release.

**Comment by mrunalabhatt** [comment]
hi @chshapiro  - thanks for your response.

Here what I have tried with my podfile
```
  pod 'Segment-Appboy', '3.3.0'
  pod 'Appboy-iOS-SDK', '3.27.0-beta1'
```

When I ran `pod install`, it gives me this error:
```
[!] CocoaPods could not find compatible versions for pod "Appboy-iOS-SDK":
  In Podfile:
    Appboy-iOS-SDK (= 3.27.0-beta1)

    Segment-Appboy (= 3.3.0) was resolved to 3.3.0, which depends on
      Segment-Appboy/Full-SDK (= 3.3.0) was resolved to 3.3.0, which depends on
        Appboy-iOS-SDK (~> 3.26.1)
```

Can you please guide me how to get both these pods installed ?

**Comment by rathishnk** [comment]
> hi @chshapiro - thanks for your response.
> 
> Here what I have tried with my podfile
> 
> ```
>   pod 'Segment-Appboy', '3.3.0'
>   pod 'Appboy-iOS-SDK', '3.27.0-beta1'
> ```
> 
> When I ran `pod install`, it gives me this error:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "Appboy-iOS-SDK":
>   In Podfile:
>     Appboy-iOS-SDK (= 3.27.0-beta1)
> 
>     Segment-Appboy (= 3.3.0) was resolved to 3.3.0, which depends on
>       Segment-Appboy/Full-SDK (= 3.3.0) was resolved to 3.3.0, which depends on
>         Appboy-iOS-SDK (~> 3.26.1)
> ```
> 
> Can you please guide me how to get both these pods installed ?

Could you try `pod install --repo-update`

**Comment by chshapiro** [comment]
Hey @mrunalabhatt,

After further investigation, the beta version of `Appboy-iOS-SDK` is not compatible with the Segment SDK. We are also unable to repro the error you are getting when pulling in version 3.26.1 of `Appboy-iOS-SDK`. Can you provide some more information about your setup - which beta version of Xcode 12 are you using? Are command line tools using Xcode 12 as well?  And are you using Apple Silicon? 

Thanks!

**Comment by mrunalabhatt** [comment]
> Hey @mrunalabhatt,
> 
> After further investigation, the beta version of `Appboy-iOS-SDK` is not compatible with the Segment SDK. We are also unable to repro the error you are getting when pulling in version 3.26.1 of `Appboy-iOS-SDK`. Can you provide some more information about your setup - which beta version of Xcode 12 are you using? Are command line tools using Xcode 12 as well? And are you using Apple Silicon?
> 
> Thanks!

May be this can be an issue : https://github.com/Appboy/appboy-ios-sdk/issues/245#issuecomment-675465529

I haven't verified with device but will try out.

**Comment by pmacro** [comment]
Hi, @chshapiro.  To be clear: there's no way to run `Segment-Appboy` when compiling against SDK 14, correct?  Because to do so requires the beta AppBoy, but there's no `Segment-Appboy` pod that depends on that rather than the latest stable `AppBoy`, hence @mrunalabhatt 's error?

Are there any plans to provide a compatible beta of `Segment-Appboy`?  Given all the IDFA changes coming in IOS 14, would be great to able to test Segment & AppBoy ahead of the release.

Thanks

**Comment by chshapiro** [comment]
Hey @pmacro, 

Have you tried compiling the current version of `Segment-Appboy` (using a stable version of `Appboy-iOS-SDK` against iOS 14? We were successful in doing so and weren't able to repro the error above. 

@pmacro and @mrunalabhatt, would it be helpful to you if we would push a branch to our repo that will depend on the beta version of `Appboy-iOS-SDK` and you can use that in your testing?

**Comment by pmacro** [comment]
@chshapiro, thanks for the quick response.

> would it be helpful to you if we would push a branch to our repo that will depend on the beta version of Appboy-iOS-SDK and you can use that in your testing?

Yeah, that would be really helpful.  Thank you!

> Have you tried compiling the current version of Segment-Appboy (using a stable version of Appboy-iOS-SDK against iOS 14? We were successful in doing so and weren't able to repro the error above.

I haven't tried with a stable version as that's not working with the Simulator, see: https://github.com/Appboy/appboy-ios-sdk/issues/245#issuecomment-675465529.  I would expect that to build for a device, though.

Thanks again.

**Comment by chshapiro** [comment]
@pmacro we will try to have that branch up within the week. Have you tested yourself using the stable version? We are able to build that on both simulator and device, and that can also be used to test some features on iOS 14.

**Comment by pmacro** [comment]
@chshapiro that's great--thanks.  I have tried the stable Appboy version: 

```
    pod 'Appboy-iOS-SDK', '3.26.1'
```

I get the error detailed in https://github.com/Appboy/appboy-ios-sdk/issues/245#issuecomment-675465529, however.

**Comment by mrunalabhatt** [comment]
Based on initial comment which I posted:
```
/Pods/Appboy-iOS-SDK/AppboyKit/libAppboyKitLibrary.a(ABKInAppMessageHTMLBase.o), building for iOS Simulator, but linking in object file built for iOS, file '//AppboyKit/libAppboyKitLibrary.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It says we are missing `libAppboyKitLibrary.a for architecture arm64`, so how about adding one for simulator build support for both the Pods. I think that should solve this problem.

**Comment by pmacro** [comment]
@mrunalabhatt they do have a fix for that issue in `pod 'Appboy-iOS-SDK', '3.27.0-beta1'`, the remaining issue, as I see it, is that there's no `Segment-Appboy` version that can work with that.  @chshapiro 's offer to push a branch of `Segment-Appboy` that depends on the fixed ` 'Appboy-iOS-SDK', '3.27.0-beta1'` should unblock this, though.

**Comment by pmacro** [comment]
A temporary workaround: set Build Active Architecture Only to YES in the Pods Xcode project for targets `Appboy-iOS-SDK` and `Segment-Appboy` using stable builds.

**Comment by chshapiro** [comment]
Hey all, 

We just released version `3.4.0-beta1` of the `Segment-Appboy` SDK which depends on the `3.27.0-beta2` version of `Appboy-iOS-SDK`. This version can be used to beta test the SDK on iOS 14 using Xcode 12.  You can integrate this version using Cocoapods but you will need to explicitly specify the beta version in your `Podfile`. 

Please let us know if this release fixes the issues you have been running into.

Thank you!

**Comment by mrunalabhatt** [comment]
@chshapiro  Thank you!

**Comment by pmacro** [comment]
Hi @chshapiro, I was wondering if you'd be able to share plans on the release of a non-beta 3.4.0, that's compatible with Xcode 12?  iOS 14 will be released tomorrow, as you may have seen.  Once the GM Xcode is available, can we expect a release fairly quickly, or could be it longer than a few days?  I'm just trying to plan a iOS 14 release of my app, and this information would help a lot!  Thank you!

**Comment by chshapiro** [comment]
Hey @pmacro,

We are testing now with GM and will release 3.4.0 within a few days.
