### ISSUE TITLE
Not compatible with official 4.1.0 Segmentent SDK release.

### ISSUE THREAD

**Issue by yawaraym** [Appboy/appboy-segment-ios#41]
Import statements are breaking in this project and does not compile. see: https://github.com/segmentio/analytics-ios/releases/tag/4.1.0

**Comment by xavierjurado** [comment]
+1, we need an update to this integration keet as soon as possible to be able to use the new iOS 14 tracking methods supported by Segment 4.1.

**Comment by chshapiro** [comment]
Hey @yawaraym and @xavierjurado,

Thanks for reporting this! We will release an update with this change in the coming days.

**Comment by xavierjurado** [comment]
Thanks @chshapiro , much appreciated!

**Comment by hassanilyas** [comment]
@chshapiro Could you give us an idea about the dates for this fix?

**Comment by chshapiro** [comment]
Hey @hassanilyas,

We hope to have this released by tomorrow the latest.

**Comment by chshapiro** [comment]
Hey all,

We just released version 3.5.0 which is compatible with 4.1.0 Segment SDK. Feel free to reopen the issue if you have any further questions.

**Comment by xavierjurado** [comment]
Thanks @chshapiro, much appreciated!

**Comment by hassanilyas** [comment]
Thanks, @chshapiro
