### ISSUE TITLE
[Request] Update to Analytics-iOS 4.1.2

### ISSUE THREAD

**Issue by iosjillian** [Appboy/appboy-segment-ios#42]
Our project is experiencing [this crash](https://github.com/segmentio/analytics-ios/issues/959) which has since been fixed in [4.1.2](https://github.com/segmentio/analytics-ios/releases/tag/4.1.2) of the Analytics-iOS library. When will an update to this library be available? Thank you so much! Normally I would wait and watch, but we're trying to get a release out the door and any sort of timeline will help!

**Comment by chshapiro** [comment]
Hey @iosjillian,

We automatically pull in the latest version of the Analytics library. Try running `pod update` and version 4.1.2 should be pulled in. Feel free to reopen the issue if you still run into issues.
