### ISSUE TITLE
Unable to import via SPM

### ISSUE THREAD

**Issue by bstillitano** [Appboy/appboy-segment-ios#46]
When importing via SPM, I receive the following error:
![image](https://user-images.githubusercontent.com/40552246/110398590-425ae600-80c8-11eb-8dbf-bb79f514937a.png)

**Comment by Bucimis** [comment]
@bstillitano what happened when you deleted the `resolved` file?

**Comment by chshapiro** [comment]
@bstillitano are you still experiencing this issue?

**Comment by bstillitano** [comment]
Seems to be working properly now, at least compiling with SPM on version 4.3.0. Important to note that the issue persists with 4.2.0. Closing issue for now.
