### ISSUE TITLE
Will there be Xamarin support?

### ISSUE THREAD

**Issue by pmahend1** [Appboy/appboy-segment-ios#47]
Hello ,

We are integrating Braze through Segment in our Xamarin Forms project.
Will you provide Xamarin bindings for this repository?

If not you could you please provide instructions how can we achieve the same behavior ? Please update documentation for this feature through Xamarin as well.

**Comment by chshapiro** [comment]
Hey @pmahend1,

We don't currently have plans to support this integration. If you would like to request this feature, you can contact your CSM to have the request tracked internally.

Thanks!
