### ISSUE TITLE
Side-by-side integration without REST API

### ISSUE THREAD

**Issue by bernikovich** [Appboy/appboy-segment-ios#48]
Hello guys
I’m trying to integrate Segment and Braze side-by-side. Documentation says that I don’t need to add Rest API key, but while trying to debug my code I noticed that this is not the case. Can you help me?

from docs:

Important: 
For the side-by-side integration, inputting the “Braze REST API Key” into your Braze’s Connection Settings in the Segment Dashboard

**Comment by chshapiro** [comment]
Hey @bernikovich,

If you're only using side-by-side inegration, you do not need to set the Rest API key. You do need to set the API Key. If you're still running into issues during debugging, please let us know what errors you are seeing.
