### ISSUE TITLE
Can we see updates from Appboy 4.2.0?

### ISSUE THREAD

**Issue by bernikovich** [Appboy/appboy-segment-ios#49]
It is as simple as updating dependency. I don't see any significant changes in the main framework. Just bug fixes that we need. Thanks! :)

**Comment by tbelote** [comment]
The significant changes are in Content Cards and News Feed, you are correct that the main framework just has bug fixes. You also should wait for 4.2.1 which should be out soon and fixes a critical bug with Classic Content Cards that have an image in them.
