### ISSUE TITLE
Bump analytics compatibility to 3.2+

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-segment-ios#5]
The current pod version is not compatible with analytics-ios 3.2. 3.2.0 is now a month old and we're at 3.2.5 as we speak.

Related issue (segment-mixpanel): https://github.com/segment-integrations/analytics-ios-integration-mixpanel/issues/11

**Comment by Wenzhi** [comment]
Hi @ldiqual,

We updated our SDK's [podspec](https://github.com/Appboy/appboy-segment-ios/blob/master/Segment-Appboy.podspec#L24) to point to analytics 3.0. So if you run `pod update`, it should update the analytics SDK to the latest 3.x version.

Did you see any issue with updating the dependency? Could you list the steps to reproduce?

Thanks,
Wenzhi

**Comment by ldiqual** [comment]
@Wenzhi My bad, it was the mixpanel pod that wasn't updated yet. All good! Thanks
