### ISSUE TITLE
How to configure in a project with a Swift AppDelegate?

### ISSUE THREAD

**Issue by molenick-mov** [Appboy/appboy-segment-ios#50]
I want to configure this for use in a new project using Swift, but the usage instructions only include Objective C instructions.

I'm able to load Segment, but I'm not sure how to go about telling the configuration to integrate with Braze:

```
        import Segment
        let segmentConfig = AnalyticsConfiguration(writeKey:"SOME-API-KEY")
        Analytics.setup(with: segmentConfig)
```

I can't find a reference to `SEGAppboyIntegrationFactory` or any way to import it.  I looked into creating bridging headers, but from what I've read it seems like this needs to be done by the package maintainers themselves.

Thank you!

**Comment by chshapiro** [comment]
Hey @molenick-mov,

Are you integrating through Cocoapods or Swift Package Manager?

**Comment by molenick-mov** [comment]
@chshapiro Swift Package Manager

**Comment by chshapiro** [comment]
Hey @molenick-mov, 

We will work on adding Swift code snippets but for now you will need to import `Full-SDK` and that will include all the files you need for this integration. We are also looking into making the name more descriptive.

**Comment by molenick-mov** [comment]
Hi @chshapiro,

It took a few tries, but I was able to import it using a bridging header (https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift).

I'll detail the steps here in case anyone else encounters this issue:
1. Add a new header file to your project (`MyProject-Bridging-Header.h`)
2. Inside, add the following: `#import "SEGAppboyIntegrationFactory.h"`
3. In your project build settings, under `Swift Compiler - General` add the path to your bridging header as the value for the `Objective-C Bridging Header` setting.

Thanks!

**Comment by TimurAsayonok** [comment]
Hello @chshapiro!
Do you have any news about when we can use `import SEGAppboyIntegrationFactory` instead of `#import "SEGAppboyIntegrationFactory.h"`?

it will really help us not to add `bridging header` solution.
Thanks!

**Comment by chshapiro** [comment]
Hey @TimurAsayonok ,

We are working on updating our [package names](https://github.com/Appboy/appboy-segment-ios/issues/44). This change will be released in the coming weeks.

**Comment by chshapiro** [comment]
Hey @TimurAsayonok ,

Please make sure that your Braze destination is set up correctly on the Segment dashboard. If you still have further questions, please reach out to Segment to help with this issue.

Thanks!
