### ISSUE TITLE
Carthage support moving forward

### ISSUE THREAD

**Issue by singhhari** [Appboy/appboy-segment-ios#51]
Hey folks,

Noticed the last two updates to the SDK do not include Carthage support but the CHANGELOG indicates a reintroduction will happen in a future version. Is there a timeline for when this will occur?

**Comment by Bucimis** [comment]
@singhhari not at the moment. Do you current have a workaround or are you working with an old Carthage-supported version?

**Comment by singhhari** [comment]
The current version we're on (4.0.0) has carthage support but we recently updated our `appboy-segment-ios` dependency and wanted to ensure there was parity between these two.

**Comment by davidbielik** [comment]
closing as we've moved to https://github.com/segment-integrations/analytics-swift-braze
