### ISSUE TITLE
Push Notifications are not getting registered in Appboy SDK

### ISSUE THREAD

**Issue by eddernunez-earnin** [Appboy/appboy-segment-ios#53]
These couple lines of code need to be refactored as these are deprecated.
https://github.com/Appboy/appboy-segment-ios/blob/0c29ca6719f2559ad966fff5bca9ed01efbb21b2/Pod/Classes/SEGAppboyIntegration.m#L286

https://github.com/Appboy/appboy-segment-ios/blob/0c29ca6719f2559ad966fff5bca9ed01efbb21b2/Pod/Classes/SEGAppboyIntegration.m#L295

This is causing test content cards to not show up in the feed and potential flaky behavior on push notifications tracking as Direct Opens.

**Comment by chshapiro** [comment]
Hey @eddernunez-earnin ,

The code you are referencing is outdated code. Please update to the latest version of the SDK and follow these [instructions](https://github.com/Appboy/appboy-segment-ios/blob/master/CHANGELOG.md#added-5) to use the `UserNotification` framework.

Thanks!
