### ISSUE TITLE
Issue opening Universal Links when app is inactive

### ISSUE THREAD

**Issue by miquelalvarado** [Appboy/appboy-segment-ios#55]
Hi,

### Context
We have found an issue with opening universal links received in remote notifications while the app is inactive (it works properly though while the app is in background or foreground). It's worth mentioning that we are using the `UNUserNotificationCenter` approach instead of the old `didReceiveRemoteNotification` way.

### Our implementation
Following [Braze documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/) we register to the notificationCenter early in AppDelegate's `didFinishLaunching:options` method as follows:
```swift
UNUserNotificationCenter.current().delegate = self
```
Then we implement userNotificationCenter delegate `didReceive` method to forward the notification the notification to the integration factory and handle it properly:
```swift
open func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
   if Appboy.sharedInstance() == nil {
        brazeIntegrationFactory?.appboyHelper.save(center, notificationResponse: response)
   } else {
        brazeIntegrationFactory?.appboyHelper.userNotificationCenter(center, receivedNotificationResponse: response)
   }
}
```
We also use the integration initialization to setup `ABKURLDelegate` and to implement `handleAppboyURL` method:
```swift
func handleAppboyURL(_ url: URL?, from channel: ABKChannel, withExtras extras: [AnyHashable: Any]?) -> Bool {
     ...
     return true
}
```

While debugging we have found that everything is called when we receive a notification from Braze until `SEGAppboyIntegration` calls the Appboy internal method `handleRemotePushNotification:withIdentifier:completionHandler:applicationState` method, which we don't have access to. After that method is called from `logPushIfComesInBeforeAppboyInitializedWithIdentifier` we lose the track and `handleAppboyURL` is never called.

Again, if the notification is received while we are in background or foreground; OR if we refactor the project to use the old `didReceiveRemoteNotification` method instead of using UserNotificationCenter, everything works as expected so we are guessing that maybe there's some kind of internal condition inside the `handleRemotePushNotification:withIdentifier:completionHandler:applicationState` that is failing somehow. 

Could you give us some kind of visibility of this issue and/or check that the implementation with userNotificationCenter is still working as expected?

**Comment by mattlsteinberg** [comment]
Hi @miquelalvarado,

Please reach out to support@braze.com with a copy of your AppDelegate, verbose logs from a reproduction of this issue, and a reference to this issue page. We'd like to take a closer look and attempt to reproduce it on our end.

Thanks!
