### ISSUE TITLE
Sample project no longer works unless SDK endpoint specified

### ISSUE THREAD

**Issue by fallaha13** [Appboy/appboy-segment-ios#58]
If you run the app you'll get an error about an invalid SDK endpoint. This used to not be the case. There should be a better way to alert people who adopt  Side by Side integration pod that the app will not work at compile time.

**Comment by chshapiro** [comment]
Hey @fallaha13,

Thanks for raising this issue. You can add your [endpoint](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration/#compile-time-endpoint-configuration-recommended) to the plist to customize the app to work with your data cluster. We will add a note about this in the repo.
