### ISSUE TITLE
Update Appboy-iOS-SDK to 4.5.1

### ISSUE THREAD

**Issue by wrbl606** [Appboy/appboy-segment-ios#65]
I noticed that this integration is using `4.4.1` version of the `Appboy-iOS-SDK` which causes conflicts with your Flutter plugin that I use: https://github.com/braze-inc/braze-flutter-sdk/blob/master/ios/braze_plugin.podspec.

The plugin uses version `4.5.1`, are there any plans for this integration to update the dependency?

**Comment by chshapiro** [comment]
Hey @wrbl606 ,

We will be releasing an updated version of the SDK next week.
