### ISSUE TITLE
Support New Segment Library `analytics-swift`

### ISSUE THREAD

**Issue by bstillitano** [Appboy/appboy-segment-ios#66]
Hi team,

Just want to check if there are any plans to support https://github.com/segmentio/analytics-swift? This library is currently one of the very last major integrations to not have added support and it is becoming an issue in newer projects.

**Comment by Bucimis** [comment]
@bstillitano support for analytics-swift is in our near term roadmap (order of ~weeks). The repo is https://github.com/braze-inc/analytics-swift-braze and you are welcome to test with it, however, the code is not considered officially released on our end yet.

**Comment by bstillitano** [comment]
Thanks @Bucimis much appreciated. Will give it a go and see how we get on.

**Comment by bstillitano** [comment]
Hi @Bucimis i have been able to migrate to the new swift SDK. Thank you for your guidance.
