### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by fareedAfzalEnt** [Appboy/appboy-segment-ios#69]
After updating my Appboy SDK to Braze Swift, I am unable to run my project after installing the Segment-Appboy SDK.

**Comment by cbowns** [comment]
@fareedAfzalEnt can you share some more info? is the project failing to compile, hanging on launch, or something else?

**Comment by hokstuff** [comment]
Hello,

I am closing out this issue due to inactivity. You can use [this updated repository](https://github.com/braze-inc/braze-segment-swift) which uses the modern Braze Swift SDK and Segment's Swift SDK.

Thanks!
