### ISSUE TITLE
Any planned updates to depend on Analytics for swift?

### ISSUE THREAD

**Issue by Germantv** [Appboy/appboy-segment-ios#71]
https://github.com/Appboy/appboy-segment-ios/blob/dc659b70f2b432f8c70fda869b27eac2acb688fe/Package.swift#L15

Is there any plans for future versions to depend on https://github.com/segmentio/analytics-swift instead of classic segment ios sdk??

**Comment by lowip** [comment]
Hi @Germantv, thanks for opening this issue.

We are planning to work on updating this integration this coming quarter. We will update here once this new repository is available.

**Comment by hokstuff** [comment]
Hi @Germantv,

You can use [this updated repository](https://github.com/braze-inc/braze-segment-swift) which uses the Braze Swift SDK and Segment's Swift SDK.

Thanks!
