### ISSUE TITLE
Support for new Braze SWIFT sdk

### ISSUE THREAD

**Issue by garlapatisatish** [Appboy/appboy-segment-ios#72]
Current Appboy-segment-ios is not compatible with new Braze Swift SDK and I see the Appboy-segment-iOS is using the OLD dependency `https://github.com/braze-inc/braze-ios-sdk.git` for braze. Any timeline or workarounds to address this issue?

**Comment by davidbielik** [comment]
Hi @garlapatisatish this is currently in development. Feel free to follow https://github.com/Appboy/appboy-segment-ios/issues/71#issuecomment-1531519890 for status updates over the next few weeks/months.
