### ISSUE TITLE
Add support for EU data centers

### ISSUE THREAD

**Issue by FiRiN59** [Appboy/appboy-segment-ios#9]
For EU data centers Appboy requires to override SDK endpoint: https://www.appboy.com/documentation/FAQs/#im-using-the-eu-database-what-do-i-need-to-do-differently

**Comment by briancaw** [comment]
Hi @FiRiN59 

Right now you can listen to when our SDK has started via https://segment.com/docs/sources/mobile/ios/#how-do-i-know-when-an-integration-is-initialized- and then set the delegate manually on the sharedInstance.  e.g.

```[Appboy sharedInstance].appboyEndpointDelegate = myDelegate```

Optionally you can also modify the `SegAppboyIntegration.m` in this repo to directly create and pass your delegate into our init method.

We'll aim to get the process more seamless in an upcoming release - please let me know if the above methods aren't working for you.

Thanks,
Brian

**Comment by FiRiN59** [comment]
Hey @briancaw,

The notification trick worked for me, thank you!
